export const PLAN_LIMITS = {
  SOLO: {
    monthlySessions: Infinity,
    maxDurationMinutes: 15,
    maxMessages: 100,
    maxPollTemplates: 2,
    canSchedule: false,
    canExport: true,
    exportFormats: ["txt"],
    canQuiz: false,
    canCustomSlug: false,
    canCustomBranding: false,
    canAiModeration: false,
    canAiClustering: false,
    canAiSummary: false,
    stageWatermark: true,
    historyRetentionDays: 7,
    isAvailable: true,
  },
  ROOM_PASS: {
    monthlySessions: Infinity,
    maxDurationMinutes: 1440, // 24 hours
    maxMessages: 500,
    maxPollTemplates: Infinity,
    canSchedule: true,
    canExport: true,
    exportFormats: ["txt", "csv"],
    canQuiz: true,
    canCustomSlug: false,
    canCustomBranding: false,
    canAiModeration: false,
    canAiClustering: false,
    canAiSummary: false,
    stageWatermark: false,
    historyRetentionDays: 30,
    isAvailable: true,
  },
  HOST: {
    monthlySessions: Infinity,
    maxDurationMinutes: 60,
    maxMessages: 1000,
    maxPollTemplates: Infinity,
    canSchedule: true,
    canExport: true,
    exportFormats: ["txt", "csv", "json"],
    canQuiz: true,
    canCustomSlug: true,
    canCustomBranding: false,
    canAiModeration: true,
    canAiClustering: false,
    canAiSummary: false,
    stageWatermark: false,
    historyRetentionDays: 90,
    isAvailable: true, // Enabled for testing and upcoming rollout
  },
  STUDIO: {
    monthlySessions: Infinity,
    maxDurationMinutes: 120,
    maxMessages: 2500,
    maxPollTemplates: Infinity,
    canSchedule: true,
    canExport: true,
    exportFormats: ["txt", "csv", "json", "pdf"],
    canQuiz: true,
    canCustomSlug: true,
    canCustomBranding: true,
    canAiModeration: true,
    canAiClustering: true,
    canAiSummary: true,
    stageWatermark: false,
    historyRetentionDays: 365,
    isAvailable: true, // Enabled for testing and upcoming rollout
  },
};